{% set name = "sphinx-wagtail-theme" %}
{% set version = "6.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinx_wagtail_theme-{{ version }}.tar.gz
  sha256: 1230607a271f99d99c28c1997a67614b8eca492d2340c4fa877f241fb5b2ac7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - sphinx-copybutton
    - python >={{ python_min }}

test:
  imports:
    - sphinx_wagtail_theme
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/wagtail/sphinx_wagtail_theme
  summary: Sphinx Wagtail theme
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
